apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: "local-storage"
  claimRef:
    name: nginx-pv
    namespace: nginx
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/media/hdd/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sicho-worker-01
