apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-nginx-pv1
  namespace: nginx1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: "local-storage"
  claimRef:
    name: web-nginx-pvc1
    namespace: nginx1
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/media/hdd/k8s/nginx/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sicho-worker-01
