apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ2bS5kc21lbnRvcmluZy5jb206NTAwMCI6eyJ1c2VybmFtZSI6ImRzbWVudG9yaW5nIiwicGFzc3dvcmQiOiJkc20xMjM0IiwiZW1haWwiOiJzaWNob0Bkc21lbnRvcmluZy5jb20iLCJhdXRoIjoiWkhOdFpXNTBiM0pwYm1jNlpITnRNVEl6TkE9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2022-11-23T00:04:37Z"
  name: dsmreg
  namespace: default
  resourceVersion: "629204"
  uid: 3ccb19c5-8d72-4bda-b972-0369fcbc610d
type: kubernetes.io/dockerconfigjson
