apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-ssh-deploy
  labels:
    app: ubuntu-ssh-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-ssh
  template:
    metadata:
      labels:
        app: ubuntu-ssh
    spec:
      hostname: ubuntu-ssh
      subdomain: dsm
      containers:
      - name: ubuntu
        image: vm.dsmentoring.com:5000/ubuntu-ssh:v4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: dsmreg
      - name: dsmregcert
      restartPolicy: Always
