apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: es
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
        resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
        securityContext:
          privileged: true
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
#          - name: discovery.type
#            value: single-node
#          - name: xpack.security.enabled # SSL 옵션 
#            value: "false"  
      initContainers:
      - name: set-dir-owner
        command:
        - sh
        - -c
        - echo 0
        - sysctl -w vm.max_map_count=262144
        - echo 0
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        - echo 0
        - chmod 777 /usr/share/elasticsearch/data
        - echo 0
        - chomod 777 /usr/share/elasticsearch/data/node
        - echo 0
        - chmod g+rwx /usr/share/elasticsearch/data
        - echo 0
        - chgrp 1000 /usr/share/elasticsearch/data
        - echo 0
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
##        - mountPath: /usr/share/elasticsearch/data
          - name: es-data
            mountPath: /tmp/test
      restartPolicy: Always
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: es-pvc
