apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-05T05:15:08Z"
  labels:
    app: httpd-svc
  name: httpd-svc
  namespace: sicho-ingress
  resourceVersion: "26025"
  uid: 351b03b2-a15e-4c20-839f-8c5697dfbc63
spec:
  clusterIP: 10.102.64.222
  clusterIPs:
  - 10.102.64.222
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd-svc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
