apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: es
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: es-pv
