apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: es
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
        resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
        securityContext:
          privileged: true
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP 
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: es-data
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
          - name: node.max_local_storage_nodes
            value: "3"
#          - name: discovery.type
#            value: single-node # 싱글 파드 환경이 아닌 멀티 파드 환경이므로 주석 처리
#          - name: xpack.security.enabled # SSL 옵션 
#            value: "false"  
      initContainers:
      - name: set-dir-owner
        command:
        - sh
        - -c
        - sysctl -w vm.max_map_count=262144
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        - chmod 777 /usr/share/elasticsearch/data
        - chomod 777 /usr/share/elasticsearch/data/node
        - chmod g+rwx /usr/share/elasticsearch/data
        - chgrp 1000 /usr/share/elasticsearch/data
#        - exit
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: es-data
      restartPolicy: Always
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: es-pvc
