kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: es
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
#  clusterIP: None
  ports:
    - port: 9200
      name: rest
      protocol: TCP
      targetPort: 9200
    - port: 9300
      name: inter-node
      protocol: TCP
      targetPort: 9300
