apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      imagePullSecrets:
      - name: registrycert
      containers:
      - name: ubuntu
        image: 192.168.0.72:5000/ubuntu-ssh:v3
        command: ["sleep", "123456"]
      nodeSelector:
        beta.kubernetes.io/os: linux
