apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox
    image: yauritux/busybox-curl #1.28
    command:
      - "tail"
      - "-f"
      - "/dev/null"
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
  restartPolicy: Always
