apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-nginx-pv
  namespace: nginx
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: web-nginx-pvc
    namespace: nginx
  local:
    path: /media/hdd/k8s/local-storage/web-nginx-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sicho-worker-01
