apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-nginx-pvc
  namespace: nginx
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: web-nginx-pv


